/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Евгения
 */
public class Docs extends javax.swing.JFrame {
Connection conn = null;
 Statement stat = null;
 ResultSet res = null;
 String userName = "root";
 String password = "Password";
 String url = "jdbc:mysql://localhost:3306/testdb";
    /**
     * Creates new form Docs
     */
    public Docs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "№ Документа", "Препарат", "Категория", "Оргинал документа", "Перевод документа", "Документ", "Статус", "Переводчик", "Дата заргузки", "Дата перевода"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Посмотреть");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Фильтр");

        jLabel2.setText("По дате");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("По категории");

        jLabel4.setText("По статусу");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Новый", "Готов", "В процессе" }));

        jLabel5.setText("По препарату");

        jLabel6.setText("По документу");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Фильтр");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("КАК РЕАЛИЗОВАТЬ МНОЖЕСТВЕННУЮ ФИЛЬТРАЦИЮ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Вывод информации о ВСЕХ документах из представления vw_docsinfo!!! Не стоит все доки показывать, ибо загрузиженный запрос!!!
         DefaultTableModel tblD = (DefaultTableModel)jTable1.getModel();
            while (tblD.getRowCount() > 0) {
            tblD.removeRow(0);
            }
        try 
    {
    Class.forName ("com.mysql.jdbc.Driver").newInstance();
    conn = DriverManager.getConnection (url, userName, password);
    stat = conn.createStatement();
    res = stat.executeQuery(" select DocumentID, CureName, CategoryName, OriginalPath, TranslatedPath, Document, Status,\n" +
                            " Sirname, InsertDate, TranslationDate from vw_docsinfo ");
    while (res.next()) {
    tblD.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), 
                res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
    }        
    jTable1.setModel(tblD);
    stat.close();
    res.close();
    }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e)
    {
    System.err.println (e.getMessage());
    } 
       finally {
        try { if ( conn != null ) { conn.close(); } } catch (Exception ignore) {}
    } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Фильтрация документа 
// если все фильтры выбраны, то
       if (!jTextField1.getText().isEmpty() || !jTextField2.getText().isEmpty() || !(jComboBox1.getSelectedItem() == null)
               || !(jComboBox2.getSelectedItem() == null) || !!(jComboBox1.getSelectedItem() == null))
        
        try {
        DefaultTableModel tblD = (DefaultTableModel)jTable1.getModel();
            while (tblD.getRowCount() > 0) {
            tblD.removeRow(0);
            }
         Class.forName ("com.mysql.jdbc.Driver").newInstance();
    conn = DriverManager.getConnection (url, userName, password);
    stat = conn.createStatement();
    res = stat.executeQuery(" select DocumentID, CureName, CategoryName, OriginalPath, TranslatedPath, Document, Status,\n" +
                            " Sirname, InsertDate, TranslationDate from vw_docsinfo \n" +
                            " where InsertDate LIKE '"+jTextField1.getText()+"%'  \n" +
                            " AND CategoryName LIKE '"+jComboBox1.getSelectedItem()+"%' AND Status = '"+jComboBox2.getSelectedItem()+"' \n" +
                            " AND CureName LIKE '"+jComboBox3.getSelectedItem()+"%' AND Document LIKE '"+jTextField2.getText()+"%' ");
    while (res.next()) {
    tblD.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), 
                res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
    }        
    jTable1.setModel(tblD);
    stat.close();
    res.close();
    }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e)
    {
    System.err.println (e.getMessage());
    } 
       finally {
        try { if ( conn != null ) { conn.close(); } } catch (Exception ignore) {}
    }  else {
           System.out.println("Что-то пошло не так");       //если не все выбраны,то
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // Проба фильтра
//        DefaultTableModel tblD = (DefaultTableModel)jTable1.getModel();
//                  
//       try 
//    {
//    Class.forName ("com.mysql.jdbc.Driver").newInstance();
//    conn = DriverManager.getConnection (url, userName, password);
//    stat = conn.createStatement();
//    res = stat.executeQuery(" select DocumentID, CureName, CategoryName, OriginalPath, TranslatedPath, Document, Status,\n" +
//                            " Sirname, InsertDate, TranslationDate from vw_docsinfo " +
//                            " WHERE Document LIKE '"+ jTextField2.getText()+"%' ");
//     while (res.next()) {
//    tblD.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), 
//                res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
//    }        
//    //jTable1.setModel(tblD);
//    stat.close();
//    res.close();
//    }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e)
//    {
//    System.err.println (e.getMessage());
//    } 
//       finally {
//        try { if ( conn != null ) { conn.close(); } } catch (Exception ignore) {}
//    } 
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Фильтр по дате
//         DefaultTableModel tblD = (DefaultTableModel)jTable1.getModel();
//              
//       try 
//    {
//    Class.forName ("com.mysql.jdbc.Driver").newInstance();
//    conn = DriverManager.getConnection (url, userName, password);
//    stat = conn.createStatement();
//    res = stat.executeQuery(" select DocumentID, CureName, CategoryName, OriginalPath, TranslatedPath, Document, Status,\n" +
//                            " Sirname, InsertDate, TranslationDate from vw_docsinfo " +
//                            " WHERE InsertDate LIKE '"+ jTextField1.getText()+"%' ");
//     while (res.next()) {
//    tblD.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), 
//                res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
//    }        
//  //  jTable1.setModel(tblD);
//    stat.close();
//    res.close();
//    }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e)
//    {
//    System.err.println (e.getMessage());
//    } 
//       finally {
//        try { if ( conn != null ) { conn.close(); } } catch (Exception ignore) {}
//    } 
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Заполнение комбо с препаратами и с категориями плохо ли это, что в одном действии сразу несолько подключений к бд?
            //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
       try 
    {
    Class.forName ("com.mysql.jdbc.Driver").newInstance();
    conn = DriverManager.getConnection (url, userName, password);
    stat = conn.createStatement();
    res = stat.executeQuery("  select CategoryName from Categories");
     while(res.next()){
    jComboBox1.addItem(res.getString(1));
     }
    stat.close();
    res.close();
    }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e)
    {
    System.err.println (e.getMessage());
    } 
       finally {
        try { if ( conn != null ) { conn.close(); } } catch (Exception ignore) {}
    } 
       
         try 
    {
    Class.forName ("com.mysql.jdbc.Driver").newInstance();
    conn = DriverManager.getConnection (url, userName, password);
    stat = conn.createStatement();
    res = stat.executeQuery("   select CureName from Cures ");
     while(res.next()) {
    jComboBox3.addItem(res.getString(1));
     }
    stat.close();
    res.close();
    }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e)
    {
    System.err.println (e.getMessage());
    } 
       finally {
        try { if ( conn != null ) { conn.close(); } } catch (Exception ignore) {}
    } 
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Docs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Docs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Docs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Docs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Docs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
